behaviors:
  PuzzleBehavior: 
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      conditioning_type: hyper
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 60000
environment_parameters:
  checkpoint_offset:
    curriculum:
      - name: Lesson0 
        completion_criteria:
          measure: reward
          behavior: PuzzleBehavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.9
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: -50  
            max_value: -45
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: PuzzleBehavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.1
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: -25
            max_value: -23
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: PuzzleBehavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.25
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: -7
            max_value: 7

